version: "3"
services:
  postgres:
    image: postgres:12.6
    volumes:
      - postgres-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: bash
    environment:
      MIX_ENV: "dev"
      PORT: "4000"
    volumes:
      - ./apps:/apps
    working_dir: /apps
    ports:
      - "4000:4000"
    tty: true
    depends_on:
      - postgres
      - mysql
volumes:
  postgres-data:
    driver: local
  mysql-data:
    driver: local
